- src/components/project-card.vue
When a project has multiple pipelines that are pending or running, show all of them in the project-card.
If none are pending or running, just show the last pipeline
> Show multiple pipelines per project

- README.md
- src/components/app.vue
Currently there is no way to show all projects in the monitor regardless of visibility. So this PR adds an 'any' option that results in no visibility filter being given to the Gitlab API. It also becomes the default, as, thinking about it logically, if a filter is not provided, then no filter should be applied.
> Add new default visibility option 'any'

- README.md
- package.json
- src/GitLabApi.js
- src/components/app.vue
- yarn.lock
For teams with a lot of projects, they can be split over multiple pages even if fetchCount is 100. So this PR adds the ability to follow the chain of next page links that the GitLab API provides, in order to build up a true list of projects. It is set to happen by default but a new followNextPageLinks query parameter is provided that enables a return to the old behaviour by setting it to false.
I made it a call-by-call option (via a new "behaviour" method parameter into $api) so the other internal API calls can make their own choice as to whether they care about a full list.
> Add support for following next page links when fetching projects

- webpack.config.js
The `VueLoaderPlugin` was only included in production, making webpack failed in development
> Fixed webpack vueLoaderPlugin, added to development too

- src/components/app.vue
Cards were being sort by a date string instead of a date instance or number
> Fixed cards sorting

- README.md
- src/components/app.vue
Add a new parameter to filter projects which have specific path prefix.
For example: `http://localhost:8080/?paths=foo/bar/` will list all projects under `foo` group and `bar` sub-group.
> Add project path prefix filter

- index.html
If you run the dashboard in a container behind a proxy, i.e. it's accessible under a certain context like "/dashboard", you encounter 404s...
> Works in context other than root

- .dockerignore
- Dockerfile
I've found your project pretty cool and I wanted to contribute to it.
I know my ways with Docker and therefore I'm proposing small optimisations.
What I've done is transform the Dockerfile into a multistage build. Meaning the first stage is only there to build the application and is "discarded" (1), the second stage picks up just the build data, nothing else.
The total build time is about the same, but the multistage approach provides the following advantages:
* Final image (the "production image") **size** is **reduced from 280MB to 20MB** (both uncompressed)
* Container **startup** time went **down from about 14s to 1s** (on my underpower laptop with a SSD)
* Container resource usage has been improved:
* **RAM** usage went **down from 55MB to 2MB**
* **IO** usage for startup went **down …
> Use Docker multistage build

- CONFIGURATION.md
- src/components/app.vue
- src/config.default.json
With larger Gitlab instances, searching projects from the whole Gitlab with API route `/projects` and filtering them from the response gets quite slow. I would be interested to monitor projects under a specific user or group. In this scenario the loading time could be reduced by using `groups/:id/projects` or `users/:id/projects` API routes.
This PR would add an option to use the above mentioned APIs, by using config parameters `projectScope` and `projectScopeId`, which default to `null`.
> Add option to search projects from under a specific user or group

- CONFIGURATION.md
- src/components/pipeline-view.vue
- src/components/stage-view.vue
- src/config.default.json
When pipeline consists of many jobs, it appears in dashboard as very long chain and is hard to be read.
Jobs names does not solve this problem because pipeline becomes too long and doesn't fit the screen. As soon as Gitlab CI pipeline consists of successive stages, it would be nice to have an option to split pipeline into stages in dashboard as well, so pipeline becomes more structured visually.
This request adds an option to expand dashes between stages and display stages names using config parameter `showStagesNames`. The default is `false`, which means no unexpected changes for users.
> Add an option to display pipeline stages names

- CONFIGURATION.md
- src/components/pipeline-view.vue
- src/config.default.json
This request adds an option to hide restarted jobs using config parameter `showRestartedJobs`. The default value is `true` and restarted jobs are visible. This implies no unexpected changes for users.
Examples:
- `showRestartedJobs: true`
- `showRestartedJobs: false`
Closes issue #85.
> Add an option to hide restarted jobs

- src/components/job-view.vue
Currently jobs names are misaligned slightly. The left padding of a bubble is too big and the right one is too small.
This request changes mentioned above paddings:
- Before:
- After:
> Fix jobs names alignment

- charts/gitlab-monitor/Chart.yaml
- charts/gitlab-monitor/templates/NOTES.txt
- charts/gitlab-monitor/templates/ingress.yaml
- charts/gitlab-monitor/templates/service.yaml
- charts/gitlab-monitor/values.yaml
This PR improve gitlab-monitor's helm/charts :
- Handle `ClusterIP` service type
- Allow to specify full ingress domain
- Allow to specify tls parameter on ingress
Feel free to propose other improvements
> [helm/chart] Improve charts

- CONFIGURATION.md
- src/components/app.vue
This PR add support for passing an Array in the parameter `projectScopeId`.
It handle default behavior with single value or with a list
Fix #96
> Allow to specify a list in projectScopeId

- src/components/app.vue
The previous logic selects all projects without tags even if an includeTags-filter is defined. If no tags are defined, the project should not be selected if a filter is defined.
> Fix filtering by project tags

- CONFIGURATION.md
- src/components/app.vue
Instead of only fetching projects under group foo, also include projects
from all subgroups that exists under group foo.
ie with the following projects:
```
├── foo (group)
│    ├── bar (group)
│    │   ├─── baz (project)
│    │   ├─── taz (project)
│    │ 
│    ├── zar (project)
```
With projectScopeId foo and include_subgroups set to true, it will now
also include the project baz and taz.  If false it would only include
zar.
Introducing own fetchCountProjects as you usually is always in crawling
all projects.
Highly recommended to be used together with https://github.com/timoschwarzer/gitlab-monitor/pull/74
> Support fetching projects from all subgroups from given group

- README.md
Will make the logo a tad more subtle.
Had to use html `<h1>` to make Github properly render the image inside the title. Also the space before 
the image is apparently necessary :shrug:
> Move logo in README.md to title and make it smaller

- CONFIGURATION.md
- src/components/pipeline-view.vue
- src/config.default.json
My team needed a way to display the test coverage of the pipelines so i implemented it into the dashboard.
The coverage is only displayed if there is data available. The coverage can be controlled ba the `showCoverage` setting and is disabled by default.
I'm not completly happy with the way that the data is displayed so input is very welcome.
> Added coverage to the pipeline view

- .gitignore
- CONFIGURATION.md
- src/components/pipeline-view.vue
- src/components/project-card.vue
- src/components/test-report.vue
- src/config.default.json
As a QA, I'm also interested in the test report from a pipeline, and since my team Gitlab show it on a pretty page I also fetched it via the API.
Following a good example of another PR (https://github.com/timoschwarzer/gitlab-monitor/pull/162), I also added a proper flag for it (showTestReport) and made sure it will only show if there's data available.
I also wanted to add the suites/tests as an accordion below that summary, but couldn't make it pretty enough and maybe unnecessary (since one can just click on the summary and see details on Gitlab), but in any case, open for suggestions there.
> Add test-report

- CONFIGURATION.md
- charts/gitlab-monitor/README.md
- charts/gitlab-monitor/values.yaml
- src/components/pipeline-view.vue
- src/components/project-card.vue
- src/config.default.json
Here is a try to to fix #165  and show detached pipelines as well.
This is achieved by
* an added project configuration `showDetached` (false per default to avoid changes for existing configurations)
* fetching a projects open merge requests (via https://docs.gitlab.com/ee/api/merge_requests.html#list-project-merge-requests)
* fetching the pipelines for these merge requests (via https://docs.gitlab.com/ee/api/merge_requests.html#list-mr-pipelines)
* adding those pipelines to the existing logic
* an updated icon and deep link in pipeline view
Additionally, a new configuration `hideSuccessfulPipelines` (false per default) to only show pipelines in non successful states  is added. Since `showProjectOnlyOn` only checks for the default branch, I feel like this is a nice additional feature to …
> Show detached pipelines

- src/components/project-card.vue
When I tried to increase the `historyCount` to something greater than 1, the page wouldn't work anymore for me.
I started looking at the possible root cause, and I found this problem (`i` could become larger than `pipelines.length`).
Once resolved, the page would work again with the same configuration as before.
> Fixed error when historyCount is greater than number of pipelines

- src/components/pipeline-view.vue
- src/components/project-card.vue
In #166 I introduced the option to show detached pipelines. Unfortunately, it's hard to keep track of the detached pipelines since only their refName (like `refs/merge-requests/132/head`) is displayed. 
Therefore, I added `refNamesAdditional` (might be used for other features as well) and added the merge requests title to this new object. Since all data was already fetched, no additional requests were necessary. The title is displayed after the refName.
> [FEAT] Added title of detached pipelines

- src/components/job-view.vue
- src/components/pipeline-view.vue
Gitlab allows a downstream pipeline to to be triggered as part
of any specific pipeline, by using the "trigger" keyword, see
https://docs.gitlab.com/ee/ci/yaml/#trigger
It looks like triggered pipelines are not included in the list
of jobs for a pipeline, but rather in a separate api,
GET /pipelines/xxx/bridges
This change checks for bridges in addition to jobs for a pipeline
and also ensures the link url from the ui targets the downstream
pipeline (this is different from a normal job url)
I'm a jvm developer with limited js experience so feel free to amend/improve/reject - I just thought I'd offer it seeing as I had written it, as I have pipelines that use "trigger:".
> Include bridge jobs in pipeline (created using trigger)

- src/components/app.vue
- src/components/runner-status.vue
- src/config.default.json
I implemented the feature requested in #161 .
Example output:
The name of the runners can be seen on hover:
I moved the `Configure` button up so it wouldn't overlap:
I didn't add a configuration option as I wasn't sure if it is needed, what are your thoughts on that ?
> Show GitLab runner status

- CONFIGURATION.md
- charts/gitlab-monitor/values.yaml
- src/components/pipeline-view.vue
- src/components/project-card.vue
- src/config.default.json
When using detached pipelines for merge requests those merge requests are often labeled. This pull requests adds a new option `showLabels` to show those labels.
The new option is enabled per default. Since `showDetached` is disabled per default it should not change anything for most users (I presume).
> Added mr labels to detached pipelines
