timoschwarzer/gitlab-monitor

- .gitignore
- README.md
- package.json
- src/components/app.vue
- src/util.js
- yarn.lock
Added parameters `groups` and `projects` that can be used to filter projects by specific groups and/or projects. 
This pr partly implements the suggested solution of issue #8
> Add project filtering

- src/components/pipeline-view.vue
- src/components/project-card.vue
Moved the `branch div` inside the pipeline, in order to show the current branch running.
This will fix #1 for now
Later it can be improve to support multi pipelines with #2
> Fixed current branch running

- src/components/pipeline-view.vue
- src/components/project-card.vue
Added links to pipelineId, current branch and project name
> Multiple links

- Dockerfile
- package.json
https://hub.docker.com/r/grebois/gitlab-monitor/
> Adding docker support

- src/components/app.vue
- src/components/project-card.vue
Latest master didn't work for me, the path filter always returned true.
Also there was an error when initially a project was null.
> fix project filter condition, ad project null check for web_url

- webpack.config.js
I seemingly have submitted a change to the wrong file today. Is this the right one to fix? Please check, thanks.
> Works in other context than root

- Dockerfile
- README.md
- package.json
- src/main.js
This PR improves docker usage in production and prompts for the required parameters if they are not present in the url query.
> Fixing Docker, prompting the token

- CONFIGURATION.md
- src/components/pipeline-view.vue
- src/components/project-card.vue
- src/config.default.json
i had some issues  for projects with many branches and pipelines. the order of pipelines were off, and sometimes the fetched branches didn't include the master branch.
* filter branches/pipelines by maxAge too
* add showMerged option to filter merged branches
* add pagination to piplines and branches
> filter and sort branches

- CONFIGURATION.md
- src/components/project-card.vue
- src/config.default.json
> fetch tags and merge with branches to refnames per pipeline

- src/components/job-view.vue
> Fix showJobNames configuration not taking effect

- CONFIGURATION.md
- src/components/job-view.vue
- src/config.default.json
> Allow to control how job icons and names are displayed

- src/components/job-view.vue
- src/components/pipeline-view.vue
Now as a pull request, see https://github.com/timoschwarzer/gitlab-monitor/issues/37
> Add tooltips and increase jobs per pipeline

- CONFIGURATION.md
Fixing invalid json caused by missing comma
> [FIX] Fix invalid json

- charts/gitlab-monitor/.helmignore
- charts/gitlab-monitor/Chart.yaml
- charts/gitlab-monitor/README.md
- charts/gitlab-monitor/templates/NOTES.txt
- charts/gitlab-monitor/templates/_helpers.tpl
- charts/gitlab-monitor/templates/deployment.yaml
- charts/gitlab-monitor/templates/ingress.yaml
- charts/gitlab-monitor/templates/service.yaml
- charts/gitlab-monitor/values.yaml
This adds a simple Kubernetes deployment mechanism for gitlab-monitor.
> add a helm chart for deployment

- CONFIGURATION.md
- src/components/app.vue
- src/components/project-card.vue
- src/config.default.json
* Goal to enter the option to list project badges in foot.
* Created the configuration badges (bool).
* Removing console.log.
> Option to insert badges

- src/main.js
> config.json is fetched from current relative path

- CONFIGURATION.md
- package.json
- src/components/app.vue
- src/config.default.json
- yarn.lock
Uses "visibilityjs" to create an interval that only calls cb when tab is active
resolves #17
> Only fetch projects when tab is active

- CONFIGURATION.md
- src/components/app.vue
- src/config.default.json
Adds orderBy option and 4 possible values: 'lastActivity', 'created', 'name', 'nameWithNamespace'
resolves #80
> Add 'orderBy' option

- CONFIGURATION.md
- THEMING.md
- package.json
- src/assets/backdrop.svg
- src/components/app.vue
- src/components/job-view.vue
- src/components/pipeline-view.vue
- src/components/project-card.vue
- src/components/stage-view.vue
- src/config.default.json
- src/themes/nord-dark.theme.scss
- src/themes/nord-light.theme.scss
- yarn.lock
This PR will add the ability to create themes and adds two new ones already. Also adds a background to the standard theme and explain how to create custom themes in `THEMING.md`. 
PS: please check for spelling errors 😬
nord-light:
nord-dark:
> Add 'theme' option and two new themes

- CONFIGURATION.md
- charts/gitlab-monitor/README.md
- charts/gitlab-monitor/values.yaml
- src/components/project-card.vue
- src/config.default.json
> Feature: Only show latest tag
